Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NewAssignment2019.Models
{
    public class Project:EntityBase
    {
        [Required]
        [StringLength(15)]
        public string Code { get; set; }

        [Required]
        [StringLength(30)]
        public string Name { get; set; }

        public Guid ClientId { get; set; }
    }
}

Areas/Admin/Pages/Client/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Client
{
    public class CreateModel : BasePageModel
    {
        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            db.Client.Add(Client);
            await db.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Client/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Client
{
    public class DeleteModel : BasePageModel
    {
        [BindProperty]
        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Client = await db.Client.FirstOrDefaultAsync(m => m.Id == id);

            if (Client == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Client = await db.Client.FindAsync(id);

            if (Client != null)
            {
                db.Client.Remove(Client);
                await db.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Client/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Client
{
    public class DetailsModel : BasePageModel
    {
        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Client = await db.Client.FirstOrDefaultAsync(m => m.Id == id);

            if (Client == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Areas/Admin/Pages/Client/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Client
{
    public class EditModel : BasePageModel
    {
        [BindProperty]
        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Client = await db.Client.FirstOrDefaultAsync(m => m.Id == id);

            if (Client == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            db.Attach(Client).State = EntityState.Modified;

            try
            {
                await db.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ClientExists(Client.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ClientExists(Guid id)
        {
            return db.Client.Any(e => e.Id == id);
        }
    }
}

Areas/Admin/Pages/Project/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;
using NewAssignment2019.Services.Project;

namespace NewAssignment2019.Areas.Admin.Pages.Project
{
    public class CreateModel : BasePageModel
    {
        [BindProperty]
        public NewAssignment2019.Models.Project Project { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Features File Upload")]
        public IFormFile UploadFeatureFile { get; set; }


        public IActionResult OnGet()
        {
            ViewData["ClientId"] = new SelectList(db.Client, "Id", "Code");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                ViewData["ClientId"] = new SelectList(db.Client, "Id", "Code");
                return Page();
            }


            using (Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction transaction = db.Database.BeginTransaction())
            {

                try
                {
                    var projectFeatureResult = await new ProjectService().UploadProjectFeaturesAsync(UploadFeatureFile, Project.Id);

                    // Perform a second check to catch ProcessFormFile method
                    // violations.
                    if (!projectFeatureResult.ModelState.IsValid)
                    {

                        ViewData["ClientId"] = new SelectList(db.Client, "Id", "Code");
                        return Page();
                    }

                    db.ProjectFeature.AddRange(projectFeatureResult.ProjectFeatures);
                    db.Project.Add(Project);

                    await db.SaveChangesAsync();

                    transaction.Commit();

                    return RedirectToPage("./Index");
                }

                catch (Exception)
                {
                    transaction.Rollback();

                    throw;
                }
            }
        }
    }
}

Areas/Admin/Pages/Project/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Project
{
    public class DeleteModel : BasePageModel
    {
        [BindProperty]
        public NewAssignment2019.Models.Project Project { get; set; }

        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project = await db.Project.FirstOrDefaultAsync(m => m.Id == id);
            Client = await db.Client.FirstOrDefaultAsync(w => w.Id == Project.ClientId);

            if (Project == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project = await db.Project.FindAsync(id);

            if (Project != null)
            {
                using (Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        db.ProjectFeature.RemoveRange(db.ProjectFeature.Where(w => w.ProjectId == Project.Id));
                        db.Project.Remove(Project);
                        await db.SaveChangesAsync();

                        transaction.Commit();
                    }
                    catch (Exception)
                    {
                        transaction.Rollback();
                        throw;
                    }
                }
            }

            return RedirectToPage("./Index");
        }
    }
}

Areas/Admin/Pages/Project/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Project
{
    public class DetailsModel : BasePageModel
    {
        public NewAssignment2019.Models.Project Project { get; set; }

        [Display(Name = "Features count")]
        public Task<int> FeaturesCount => db.ProjectFeature.Where(w => w.ProjectId == Project.Id).CountAsync();
        public NewAssignment2019.Models.Client Client { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project = await db.Project.FirstOrDefaultAsync(m => m.Id == id);
            Client = await db.Client.FirstOrDefaultAsync(w => w.Id == Project.ClientId);

            if (Project == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Areas/Admin/Pages/Project/Edit.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Models;
using NewAssignment2019.Services.Project;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace NewAssignment2019.Areas.Admin.Pages.Project
{
    public class EditModel : BasePageModel
    {
        private readonly IMapper mapper;

        public EditModel(IMapper mapper)
        {
            this.mapper = mapper;
        }

        [BindProperty]
        public NewAssignment2019.Models.Project Project { get; set; }

        [Display(Name = "Features File Upload")]
        public IFormFile UploadFeatureFile { get; set; }

        [Display(Name = "Feature Count")]
        public int FeatureCount { get; set; }

        public List<ProjectSprintVM> ProjectSprints { get; private set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Project = await db.Project.FirstOrDefaultAsync(m => m.Id == id);

            if (Project == null)
            {
                return NotFound();
            }

            IOrderedQueryable<Models.ProjectSprint> projectSprints = db.ProjectSprint.Where(w => w.ProjectId == Project.Id).OrderBy(o => o.DateBegin);
            ProjectSprints = this.mapper.Map<IOrderedQueryable<Models.ProjectSprint>, List<ProjectSprintVM>>(projectSprints);

            foreach (ProjectSprintVM item in ProjectSprints)
            {
                var fc = new ProjectService().GetBacklogs(item.Id).Count();
                item.SetFeatureCount(fc);
            }

            FeatureCount = await db.ProjectFeature.Where(w => w.ProjectId == Project.Id).CountAsync();


            ViewData["ClientId"] = new SelectList(db.Client, "Id", "Code");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Project.ModifiedDate = DateTime.UtcNow;
            Project.ModifiedBy = User.Identity.Name;

            db.Attach(Project).State = EntityState.Modified;

            using (Microsoft.EntityFrameworkCore.Storage.IDbContextTransaction transaction = db.Database.BeginTransaction())
            {
                try
                {
                    await db.SaveChangesAsync();

                    transaction.Commit();

                    return RedirectToPage("./Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    transaction.Rollback();

                    if (!ProjectExists(Project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
        }


        public async Task<IActionResult> OnPostUploadFeatureFileAsync()
        {
            try
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile f = Request.Form.Files[0];

                    (IEnumerable<ProjectFeature> ProjectFeatures, Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary ModelState) projectFeatureResult = await new ProjectService().UploadProjectFeaturesAsync(f, Project.Id);

                    // Perform a second check to catch ProcessFormFile method
                    // violations.
                    if (!projectFeatureResult.ModelState.IsValid)
                    {
                        return Page();
                    }

                    db.ProjectFeature.AddRange(projectFeatureResult.ProjectFeatures);

                    await db.SaveChangesAsync();
                }
            }
            catch (Exception)
            {
                throw;
            }

            //Project = await db.Project.FirstOrDefaultAsync(m => m.Id == Project.Id);
            //ProjectSprint = await db.ProjectSprint.Where(w => w.ProjectId == Project.Id).ToListAsync();
            //FeatureCount = await db.ProjectFeature.Where(w => w.ProjectId == Project.Id).CountAsync();
            //ViewData["ClientId"] = new SelectList(db.Client, "Id", "Code");

            //ModelState.Clear();

            //return Page();

            return RedirectToPage("Edit", new { id = Project.Id });
        }

        private bool ProjectExists(Guid id)
        {
            return db.Project.Any(e => e.Id == id);
        }

        public class ProjectSprintVM : Models.ProjectSprint
        {
            private int featureCount = 0;
            public int FeatureCount => featureCount;

            public void SetFeatureCount(int featureCount)
            {
                this.featureCount = featureCount;
            }
        }

        public class ProjectSprintMappingProfile : Profile
        {
            public ProjectSprintMappingProfile()
            {
                CreateMap<Models.ProjectSprint, ProjectSprintVM>();
            }
        }
    }
}

Areas/Admin/Pages/Project/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NewAssignment2019.Base;
using NewAssignment2019.Data;
using NewAssignment2019.Models;

namespace NewAssignment2019.Areas.Admin.Pages.Project
{
    public class IndexModel : BasePageModel
    {
        public IList<ProjectClient> ProjectClients { get; set; }

        public async Task OnGetAsync()
        {
            ProjectClients = await (from p in db.Project
                                    join c in db.Client on p.ClientId equals c.Id
                                    select new ProjectClient
                                    {
                                        Id = p.Id,
                                        Code = p.Code,
                                        Name = p.Name,
                                        Client = c
                                    }).ToListAsync();
        }

        public class ProjectClient : Models.Project
        {
            public Models.Client Client { get; set; }
        }
    }
}

Areas/Admin/Pages/Project/Create.cshtml
@page
@model NewAssignment2019.Areas.Admin.Pages.Project.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Project.Code" class="control-label"></label>
                <input asp-for="Project.Code" class="form-control" />
                <span asp-validation-for="Project.Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Project.Name" class="control-label"></label>
                <input asp-for="Project.Name" class="form-control" />
                <span asp-validation-for="Project.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Project.ClientId" class="control-label"></label>
                <select asp-for="Project.ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UploadFeatureFile" class="control-label"></label>
                <input asp-for="UploadFeatureFile" type="file" class="form-control" style="height:auto" />
                <span asp-validation-for="UploadFeatureFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Pages/Project/Delete.cshtml
@page
@model NewAssignment2019.Areas.Admin.Pages.Project.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.CreatedBy)
        </dd>
    </dl>

    <form method="post">
        <input type="hidden" asp-for="Project.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Areas/Admin/Pages/Project/Details.cshtml
@page
@model NewAssignment2019.Areas.Admin.Pages.Project.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Client.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Project.ModifiedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Project.ModifiedBy)
        </dd>
        <dt class="col-sm-2">
            Features Count
        </dt>
        <dd class="col-sm-10">
            @Model.FeaturesCount.Result
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Project.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Areas/Admin/Pages/Project/Edit.cshtml
@page
@model NewAssignment2019.Areas.Admin.Pages.Project.EditModel

@{
    ViewData["Title"] = "Edit Project";
}

<link rel="stylesheet" href="~/css/table-responsive.css" />
<h1>@ViewData["Title"] </h1>


<table width="100%" >
    <tr style="vertical-align:top">
        <td id="leftPane" style="width:100%; padding:10px" class="table">
            <div class="row">
                <div class="col-md-12">
                    <form method="post" class="form-group">
                        <input type="hidden" asp-for="Project.Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Project.Code" class="control-label"></label>
                            <input asp-for="Project.Code" class="form-control" />
                            <span asp-validation-for="Project.Code" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Project.Name" class="control-label"></label>
                            <input asp-for="Project.Name" class="form-control" />
                            <span asp-validation-for="Project.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Project.ClientId" class="control-label"></label>
                            <select asp-for="Project.ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                            <span asp-validation-for="Project.ClientId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-arrow-circle-right fa-lg"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </td>

        <td id="rightPane" style="width:100%; vertical-align:top; padding:10px">
            <div tabindex="0" class="e-card" id="features">
                <div class="e-card-header">
                    <div class="e-card-header-caption">
                        <div class="e-card-header-title">Features <span class="e-badge e-badge-success e-badge-pill">@Model.FeatureCount</span></div>
                        <div class="e-card-sub-title">There are a total of @Model.FeatureCount features for this project.</div>
                    </div>
                </div>
                <div class="e-card-content">
                    <div class="row">
                        <div class="col-md-4" style="text-align:center">
                            <a asp-page="." asp-route-projectId="@Model.Project.Id">
                                <i class="fa fa-download fa-2x"></i>
                            </a>
                            <br />
                            Download feature upload template
                        </div>

                        <div class="col-md-4" style="text-align:center">
                            <form method="post" asp-page-handler="UploadFeatureFile" enctype="multipart/form-data" class="form-group">
                                <input type="hidden" asp-for="Project.Id" />
                                <div style="cursor: pointer;" onclick="$('#inputUpload').click(); return false;">
                                    <a class="fa fa-upload red fa-2x"></a>
                                    <label asp-for="UploadFeatureFile" class="control-label" style="cursor: pointer;"></label>
                                </div>

                                <input id="inputUpload" name="inputUpload" asp-for="UploadFeatureFile" onchange="this.form.submit();"
                                       type="file" style="display: none;">
                            </form>
                        </div>

                        <div class="col-md-4" style="text-align:center">
                            <a asp-page="../ProjectFeatures/Index" asp-route-projectId="@Model.Project.Id">
                                <i class="fa fa-table fa-2x"></i>
                            </a>
                            <br />
                            View all features
                        </div>
                    </div>
                </div>
            </div>
            <br />

            <div tabindex="0" class="e-card" id="sprints">
                <div class="e-card-header">
                    <div class="e-card-header-caption">
                        <div class="e-card-header-title">
                            Sprints (@Model.ProjectSprints.Count())
                            <a asp-page="../ProjectSprint/Create" asp-route-projectId="@Model.Project.Id">
                                <i class="fa fa-plus-square"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="e-card-content">
                    <table class="table table-hover table-responsive table-borderless" style="width:100%">
                        <tbody>
                            @foreach (var item in Model.ProjectSprints)
                            {
                                <tr>
                                    <td width="100%">
                                        [<label>@item.Code</label>] <label>@item.Name</label> (<label>@item.FeatureCount feats.</label>)
                                        <br />
                                        <div nowrap>
                                            <label>@item.DateBegin.ToString("dd MMM")</label> - <label>@item.DateEnd.ToString("dd MMM yyyy")</label>
                                            <a asp-page="../ProjectSprint/Edit" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                            <a asp-page="../ProjectSprint/Details" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                                            <a asp-page="../ProjectSprint/Delete" asp-route-id="@item.Id"><i class="fa fa-trash red"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </td>
    </tr>
</table>





<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Pages/Project/Index.cshtml
@page
@model NewAssignment2019.Areas.Admin.Pages.Project.IndexModel

@{
    ViewData["Title"] = "Project List";
}

<h1>@ViewData["Title"] <a asp-page="Create"><i class="fa fa-plus-square"></i></a></h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProjectClients[0].Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectClients[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProjectClients[0].ClientId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ProjectClients)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.Code)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                    <a asp-page="./Details" asp-route-id="@item.Id"><i class="fa fa-eye"></i></a>
                    <a asp-page="./Delete" asp-route-id="@item.Id"><i class="fa fa-trash red"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>